trigger:
  batch: true
  branches:
    include:
    - master

pool:
  vmImage: 'Ubuntu-22.04'

variables:
  BuildConfiguration: 'release'
  BuildPlatform: 'any cpu'
  DOTNET_NOLOGO: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true


stages:
  - stage: Compile
    displayName: 'Compile'
    pool:
      vmImage: 'Ubuntu-22.04'
    jobs:
      - job: Compile
        displayName: 'Compile'
        steps:
          - task: UseDotNet@2
            displayName: "Use .Net Core SDK 9.0"
            inputs:
              packageType: 'sdk'
              version: '9.0.x'
          - task: CmdLine@2
            inputs:
              script: './build.sh Test'
