#!/usr/bin/env bash
if ! head -1 "$1" | grep -qE "^(feat|fix|build|chore|ci|docs|style|refactor|perf|test)(\(.+?\))?: .{1,}$"; then
    echo "Aborting commit. Your commit message is invalid." >&2
    echo "See https://www.conventionalcommits.org/en/v1.0.0/#summary for details of the correct format." >&2
    exit 1
fi
if ! head -1 "$1" | grep -qE "^.{1,50}$"; then
    echo "Aborting commit. Your commit message is too long." >&2
    exit 1
fi